# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'VIP test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VIP test

    pod 'Alamofire', '~> 4.7'
    pod 'AlamofireObjectMapper', '~> 5.2'
    #pod 'ShappMiddlewareClientPod', :git => 'https://github.com/JorgeMoralesLiverpool/ShappMiddlewareClientPod.git', :branch => 'master'

  target 'VIP testTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VIP testUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
