//
//  ProductsListWorker.swift
//  VIP test
//
//  Created by LFNAVAR on 2/20/19.
//  Copyright (c) 2019 LFNAVAR. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ProductsListWorker
{
    // Initialize the variable with a type ProductProtocol Class
    // that help us to change the API Service
    var productsStore: ProductProtocol
    
    init(productsStore: ProductProtocol)
    {
        self.productsStore = productsStore
    }
    
    // Function that does the work with the API Service to get the data
    func fetchProducts(completionHandler: @escaping ([Products]) -> Void)
    {
        productsStore.fetchProducts { (products: [Products]) -> Void in
                DispatchQueue.main.async {
                    completionHandler(products)
                }
            
        }
    }
}

// Contain the functions of the calls to the API
protocol ProductProtocol
{
    func fetchProducts(completionHandler: @escaping ([Products]) -> Void)
}
