//
//  ProductsListRouter.swift
//  VIP test
//
//  Created by LFNAVAR on 2/20/19.
//  Copyright (c) 2019 LFNAVAR. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// Protocol that is called for the view controller for routing to detail Product scene
@objc protocol ProductsListRoutingLogic
{
  func routeToDetailProduct(segue: UIStoryboardSegue?)
}

// protocol that receive the data from the interactor, this data is sent to detail Product scene and received for the protocol inside DetailProductRouter. if you see is a variable ProductsListDataStore type, is the name of the protocol in the interactor
protocol ProductsListDataPassing
{
  var dataStore: ProductsListDataStore? { get }
}

class ProductsListRouter: NSObject, ProductsListRoutingLogic, ProductsListDataPassing
{
  weak var viewController: ProductsListViewController?
  var dataStore: ProductsListDataStore?
  
  // MARK: Routing to detail product scene
  func routeToDetailProduct(segue: UIStoryboardSegue?)
  {
    if let segue = segue {
        let destinationVC = segue.destination as! DetailProductViewController
        var destinationDS = destinationVC.router!.dataStore
        passDataToSomewhere(source: self.dataStore!, destination: &destinationDS!)
    } else {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "DetailProductVC") as! DetailProductViewController
        var destinationDS = destinationVC.router?.dataStore!
        passDataToSomewhere(source: self.dataStore!, destination: &destinationDS!)
        navigateToSomewhere(source: self.viewController!, destination: destinationVC)
    }
  }

  // MARK: Navigation to another view controller
  
  func navigateToSomewhere(source: ProductsListViewController, destination: DetailProductViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data to protocol in the scene router
  
  func passDataToSomewhere(source: ProductsListDataStore, destination: inout DetailProductDataStore)
  {
    let selectedRow = viewController?.tableView.indexPathForSelectedRow?.row
    destination.products = source.products?[selectedRow!]

  }
}
