//
//  ProductsListModels.swift
//  VIP test
//
//  Created by LFNAVAR on 2/20/19.
//  Copyright (c) 2019 LFNAVAR. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Model for this scene, when you work with an API call you need:
/// Request: parameters that need to be sent
/// Response: the response from the API
/// View Model: the data that you need to show in the view
struct ProductsList {
    
    // the struct is nested because probably in a scene you need another struct for other elements for example probably you need a struct for update or post data
    struct FetchProducts {
        struct Request {
        
        }
        
        struct Response {
            var products: [Products]
        }
        
        struct ViewModel {
            struct DisplayedProduct {
                var stationName: String
                var statusValue: String
                var route: Bool
            }
            var displayedProducts: [DisplayedProduct]
        }
    }
}
