//
//  DetailProductWorker.swift
//  VIP test
//
//  Created by LFNAVAR on 2/21/19.
//  Copyright (c) 2019 LFNAVAR. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class DetailProductWorker
{
  func doSomeWork()
  {
  }
}
