//
//  DetailProductModels.swift
//  VIP test
//
//  Created by LFNAVAR on 2/21/19.
//  Copyright (c) 2019 LFNAVAR. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct DetailProduct
{
    // MARK: Use cases
    
    struct GetProduct
    {
        struct Request
        {
        }
        struct Response
        {
            var products: Products
        }
        struct ViewModel
        {
            struct DisplayedProduct
            {
                var stationName: String
                var latitude: Double
                var longitude: Double
                var availableBikes: Int
                var statusValue: String
            }
            var displayedProducts: DisplayedProduct
        }
    }
}
