//
//  ProductsWorker.swift
//  VIP test
//
//  Created by LFNAVAR on 2/20/19.
//  Copyright (c) 2019 LFNAVAR. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

//class ProductsWorker
//{
//    var productsStore: ProductProtocol
//
//    init(productsStore: ProductProtocol)
//    {
//        self.productsStore = productsStore
//    }
//    
//    func fetchProducts(completionHandler: @escaping ([Products]) -> Void)
//    {
//        productsStore.fetchProducts { (products: () throws -> [Products]) -> Void in
//            do {
//                let product = try products()
//                DispatchQueue.main.async {
//                    completionHandler(product)
//                }
//            } catch {
//                DispatchQueue.main.async {
//                    completionHandler([])
//                }
//            }
//        }
//    }
//
//}
//
//protocol ProductProtocol
//{
//    func fetchProducts(completionHandler: @escaping (() throws -> [Products]) -> Void)
//}

